<a href="https://colab.research.google.com/github/japs2024/Repo1/blob/main/example_for_one_way_anova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from scipy.stats import f

# Given data
school_1 = np.array([85, 88, 90, 92, 86])
school_2 = np.array([78, 82, 80, 85, 88])
school_3 = np.array([92, 94, 89, 88, 90])

In [3]:
# Step 1: Calculate Grand Mean
all_scores = np.concatenate([school_1, school_2, school_3])
grand_mean = np.mean(all_scores)

In [4]:
# Step 2: Calculate SST
sst = np.sum((all_scores - grand_mean)**2)

In [5]:
# Step 3: Calculate SSB
ssb = np.sum([len(school) * (np.mean(school) - grand_mean)**2 for school in [school_1, school_2, school_3]])

In [6]:
# Step 4: Calculate SSW
ssw = np.sum([(score - np.mean(school))**2 for school, scores in zip([school_1, school_2, school_3], [school_1, school_2, school_3]) for score in scores])

In [7]:
# Step 5: Degrees of Freedom
df_between = 3 - 1
df_within = len(all_scores) - 3

In [8]:
# Step 6: Calculate Mean Squares
msb = ssb / df_between
msw = ssw / df_within

In [9]:
# Step 7: Calculate F-statistic
f_statistic = msb / msw

In [10]:
# Step 8: Compare with Critical Value or P-value
p_value = 1 - f.cdf(f_statistic, df_between, df_within)

In [11]:
# Print results
print(f"F-statistic: {f_statistic}")
print(f"P-value: {p_value}")

alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: \nThere are significant differences in test scores among the three schools.")
else:
    print("Fail to reject the null hypothesis: \nThere are no significant differences in test scores among the three schools.")

F-statistic: 8.483221476510069
P-value: 0.005054945419651569
Reject the null hypothesis: 
There are significant differences in test scores among the three schools.


In [14]:
# prompt: generale a random list with commas with 10 numbers

import random
random_list = [str(random.randint(0, 100)) for _ in range(10)]
print(', '.join(random_list))


23,80,46,50,30,86,33,29,23,1


In [ ]:
import numpy as np
from scipy.stats import f

# Given data
school_1 = np.array([85, 88, 90, 92, 86])
school_2 = np.array([78, 82, 80, 85, 88])
school_3 = np.array([92, 94, 89, 88, 90])


In [17]:
# prompt: zip arrays

import numpy as np
zipped_arrays = np.stack((school_1, school_2, school_3), axis=1)
print(zipped_arrays)


[[85 78 92]
 [88 82 94]
 [90 80 89]
 [92 85 88]
 [86 88 90]]


zip examples